User/kyuhwan
neoul-gaji/WebsiteFE pull request #4
Opened 2021-02-21 14:58 UTC by Aiden-Kwak

2021-02-21 15:23 UTC, Aiden-Kwak commented on src/views/identity/Register.vue
> +  }
select 주는거 보다 사용자가 정의하게하는게 나을듯

2021-02-21 15:26 UTC, Aiden-Kwak reviewed
나중에 부트스트랩 사용한거 정리좀 해주십

2021-02-21 15:26 UTC, Aiden-Kwak commented on src/views/identity/Register.vue
> +</style>
부트스트랩 사용을 권장해도 그거 변환하려면 결국 style만들어야하는데 나중에 통합관리해도 결국 걱정하던 건 해결이 안될거같은데

2021-02-21 15:52 UTC, Just4Study commented on src/views/identity/Register.vue
> +</style>
style 아예 넣지 말라는 건 아닌데 지금 이 정도면 좀 과함

2021-02-22 07:43 UTC, underthelights commented on src/views/identity/Register.vue
> +  }
사용자 정의라면 어떻게? 서울대를 예로 들면 '서울대학교' '서울대' 'SNU'이렇게 되고 과기원은 더 다양해짐. 선택해서 하는 게 통일성 있지 않을까? 에브리타임은 일단 하드코딩으로 모든 대학들 넣어 두었더라

2021-02-22 07:43 UTC, underthelights commented on src/views/identity/Register.vue
> +</style>
css 관한 것은 이야기를 더 해봐야 할 듯!

2021-02-22 07:47 UTC, underthelights reviewed
bootstrap + <style>

2021-02-22 07:47 UTC, underthelights commented on src/views/identity/Register.vue
> +  }
bootstrap : 
- (1) form checkbox : [link](https://bootstrap-vue.org/docs/components/form-checkbox)
- 약관 동의 체크박스
- (2) form select : [link](https://bootstrap-vue.org/docs/components/form-select)
- 대학 선택 창
- (3) form 에서 e-mail : [link](https://bootstrap-vue.org/docs/components/form)
- 이메일 링크 박스

2021-02-22 09:55 UTC, Just4Study approved these changes
지금 할 것도 많고 회원가입, 로그인, reset id/pw 페이지는 간단하니까 일단 그냥 merge 하는 걸로 합시다.

2021-02-22 10:00 UTC, Just4Study requested changes
1. nav라는 div tag는 필요 없으니까 관련된 style, html 태그 다 빼주세요.
2. router-view tag 빼주세요.
3. 약관을 맨 밑에 넣어도 될 듯?
4. password input type을 password로 해주셔야 합니다.
5. 근데 왜 회원가입하는데 id도 없죠? 
6. 단순히 글만 들어간 부분은 p tag 사용해주세요
7. 로그인 부분 link 걸어주세요 /login

+ 회원 가입 양식 좀 보완 해주세용!

2021-02-22 12:25 UTC, underthelights commented
> 1. nav라는 div tag는 필요 없으니까 관련된 style, html 태그 다 빼주세요.
> 2. router-view tag 빼주세요.
> 3. 약관을 맨 밑에 넣어도 될 듯?
> 4. password input type을 password로 해주셔야 합니다.
> 5. 근데 왜 회원가입하는데 id도 없죠?
> 6. 단순히 글만 들어간 부분은 p tag 사용해주세요
> 7. 로그인 부분 link 걸어주세요 /login (bootstrap에 b-link라는 놀라운 tag가 있답니다.)
> 
> * 회원 가입 양식 좀 보완 해주세용!

5. 회원가입을 메일로 하면 되는거 아니냐? 차피 대학 인증 받아서 하는 형식일텐데?

2021-02-24 16:46 UTC, underthelights commented
여기 pr 닫아주세요!

2021-02-25 08:10 UTC, closed without merging