User/kewonn
neoul-gaji/WebsiteFE pull request #9
Opened 2021-02-25 19:48 UTC by Aiden-Kwak

ResetPassword by kewonn

2021-02-25 19:50 UTC, Aiden-Kwak commented on ResetPassword.vue
> +    <div id="container">
돌려봤을때 준 사진이랑 다른데, 아마 app서 만들었다고 생각됨. app에는 center align되었는데 그거 없애서 그런걸거임. container 중앙정렬 ㄱ

2021-02-25 19:52 UTC, Aiden-Kwak commented on ResetPassword.vue
> +// 이메일로 인증번호를 받고 비밀번호를 변경하는 page
계원이가 업로드하려는데 Uploads are disabled. File uploads require push access to this repository. 라고 뜨더라.
영욱이 권한설정 확인바람

2021-02-26 17:52 UTC, Just4Study requested changes
**수정 요청 사항**

1. 글씨만 들어간 부분은 div 대신 p 혹은 span tag
2. App.vue의 #app 부분의 text-align을 없애야 됨 -> text-align: left 지워도 됨
3. b tag 말고 다른 방법 없을까?

2021-02-27 07:04 UTC, underthelights commented
- 수정권고 사항
- 1. 처음 딱 들어갈 때, '새로운 비밀번호를 정확히 다시 입력해주세요(newpasswordcheck)" 부분은 초록색으로 떠야 됨. "새로운 비밀번호를 입력해주세요(newpassword)"부분도 빈칸이기 때문에, 당연하게도 newpasswordcheck 부분은 위와 맡는지가 중요한 여부이기 때문에, 비록 10자 이내의 문자로 check에 입력하더라도 기능을 수행해야 한다는 개인적인 생각이 듬.
- 2. button 또한 bootstrap 을 활용한 리디자인 
- 3. 앞서 영욱 병혁이가 말했듯, app.vue에 해당 사항을 적용한 후 가운데 정렬을 별개로 여기에 구현할 것.

- 기타
- 1. 내거 register.vue에서와 동일한 비밀번호 규격을 상의 후 결정해야 할듯? 몇 글자 이상으로 할지, 저기 글자들은 몇 포인트로 할 지 등등.
- 2. alert, bootstrap 잘 사용한 듯!

2021-03-06 05:27 UTC, closed without merging